version: "3.3"
services:
  database:
    container_name: database-GCS
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  php:
    container_name: php-GCS
    user: ${USER_ID}
    build:
      context: api/docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/api
    depends_on:
      - database
  frontend:
    build:
      context: ./client-front
      dockerfile: docker/Dockerfile
    user: ${USER_ID}
    ports:
      - "4200:4200"
    container_name: angular-GCS
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app/client-front && npm install --legacy-peer-deps && npm start
    volumes:
      - ./client-front:/usr/src/app/client-front
      - ./client-front/node_modules:/usr/src/app/client-front/node_modules

  nginx:
    container_name: nginx-GCS
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/api
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
      - frontend
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
    - "1080:1080"
    - "1025:1025"

networks:
  dev:

volumes:
  mysql-data:
