<?php

namespace App\DataFixtures;

use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Faker\Factory;

class AppFixtures extends Fixture
{
    public function __construct(UserPasswordHasherInterface $passwordHasher)
    {
         $this->passwordHasher = $passwordHasher;
         $this->faker =Factory::create();
    }

        public function load(ObjectManager $manager)
    {
        $this->loaduser($manager);
    }
    public function loaduser(ObjectManager $manager)
    { 
        $myRoles = [User::ROLE_ADMIN, User::ROLE_USER];
        for ($i=0; $i<10; $i++ ){
            $user = new User();
            $user->setEmail($this->faker->email);
            $user->setName($this->faker->name);
            $user->setAdress($this->faker->address);
            $user->setRoles([$myRoles[rand(0,1)]]);
            $user->setCreateAt(new \DateTimeImmutable());
            $user->setUpdatedAt(new \DateTimeImmutable());
            $user->setPassword($this->passwordHasher->hashPassword($user,'123456'));
            $user->setSolde(rand(0,20));
            $manager->persist($user);
        }


        $manager->flush();
    }

    public function addReference($name, $object)
    {
        parent::addReference($name, $object); // TODO: Change the autogenerated stub
    }
}
